apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smartdoc-ai
  labels:
    app: frontend
    tier: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: ui
    spec:
      containers:
        - name: frontend
          image: 479537131188.dkr.ecr.us-east-1.amazonaws.com/smartdoc-frontend:sha-d2fc273
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              sed -i 's|http://localhost:8000|http://backend.smartdoc-ai.svc.cluster.local:8000|g' .next/routes-manifest.json
              exec node server.js
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: INTERNAL_BACKEND_URL
              value: "http://backend.smartdoc-ai.svc.cluster.local:8000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: smartdoc-ai
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: frontend
