global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "smartdoc-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          service: "smartdoc-backend"
          tier: "application"
          env: "production"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
